// Shared mock data for all portals (Admin, Tenant, Landlord)

export const mockProperties = [
  {
    id: '1',
    name: 'Sunset Apartments',
    address: '123 Main Street, Downtown',
    units: 8,
    occupied: 8,
    totalRent: 320000,
    landlordId: '1',
    landlord: 'James K. Johnson',
    status: 'Active',
    yearBuilt: 2015,
    type: 'Apartment',
  },
  {
    id: '2',
    name: 'Vista Plaza',
    address: '456 Oak Avenue, Uptown',
    units: 12,
    occupied: 8,
    totalRent: 480000,
    landlordId: '2',
    landlord: 'Sarah M. Williams',
    status: 'Active',
    yearBuilt: 2018,
    type: 'Apartment',
  },
  {
    id: '3',
    name: 'Highland House',
    address: '789 Pine Road, Midtown',
    units: 6,
    occupied: 3,
    totalRent: 180000,
    landlordId: '3',
    landlord: 'Robert J. Brown',
    status: 'Active',
    yearBuilt: 2012,
    type: 'Townhouse',
  },
  {
    id: '4',
    name: 'Garden Estate',
    address: '321 Elm Street, Riverside',
    units: 10,
    occupied: 9,
    totalRent: 360000,
    landlordId: '4',
    landlord: 'Patricia L. Davis',
    status: 'Active',
    yearBuilt: 2019,
    type: 'Apartment',
  },
]

export const mockTenants = [
  {
    id: '1',
    name: 'John Smith',
    email: 'john.smith@email.com',
    phone: '+254 712 345 678',
    idNumber: '12345678',
    property: 'Sunset Apartments',
    propertyId: '1',
    landlordId: '1',
    unit: '5A',
    rent: 40000,
    status: 'Active',
    moveIn: '2023-06-15',
    moveOut: null,
    leaseEnd: '2025-06-14',
    emergencyContact: 'Jane Smith',
    emergencyPhone: '+254 712 111 111',
  },
  {
    id: '2',
    name: 'Sarah Johnson',
    email: 'sarah.j@email.com',
    phone: '+254 722 567 890',
    idNumber: '87654321',
    property: 'Vista Plaza',
    propertyId: '2',
    landlordId: '2',
    unit: '3B',
    rent: 40000,
    status: 'Active',
    moveIn: '2023-08-22',
    moveOut: null,
    leaseEnd: '2025-08-21',
    emergencyContact: 'Robert Johnson',
    emergencyPhone: '+254 722 222 222',
  },
  {
    id: '3',
    name: 'Michael Chen',
    email: 'michael.chen@email.com',
    phone: '+254 733 789 456',
    idNumber: '11111111',
    property: 'Highland House',
    propertyId: '3',
    landlordId: '3',
    unit: '2C',
    rent: 30000,
    status: 'Active',
    moveIn: '2023-11-01',
    moveOut: null,
    leaseEnd: '2025-10-31',
    emergencyContact: 'Lisa Chen',
    emergencyPhone: '+254 733 333 333',
  },
  {
    id: '4',
    name: 'Emma Wilson',
    email: 'emma.w@email.com',
    phone: '+254 744 012 345',
    idNumber: '22222222',
    property: 'Sunset Apartments',
    propertyId: '1',
    landlordId: '1',
    unit: '8D',
    rent: 40000,
    status: 'Active',
    moveIn: '2023-09-15',
    moveOut: null,
    leaseEnd: '2025-09-14',
    emergencyContact: 'Thomas Wilson',
    emergencyPhone: '+254 744 444 444',
  },
  {
    id: '5',
    name: 'David Martinez',
    email: 'david.m@email.com',
    phone: '+254 755 234 567',
    idNumber: '33333333',
    property: 'Garden Estate',
    propertyId: '4',
    landlordId: '4',
    unit: '6F',
    rent: 36000,
    status: 'Active',
    moveIn: '2023-07-10',
    moveOut: null,
    leaseEnd: '2025-07-09',
    emergencyContact: 'Rosa Martinez',
    emergencyPhone: '+254 755 555 555',
  },
  {
    id: '6',
    name: 'Lisa Anderson',
    email: 'lisa.a@email.com',
    phone: '+254 766 456 789',
    idNumber: '44444444',
    property: 'Vista Plaza',
    propertyId: '2',
    landlordId: '2',
    unit: '9G',
    rent: 40000,
    status: 'Active',
    moveIn: '2023-10-05',
    moveOut: null,
    leaseEnd: '2025-10-04',
    emergencyContact: 'Mark Anderson',
    emergencyPhone: '+254 766 666 666',
  },
  {
    id: '7',
    name: 'James Taylor',
    email: 'james.t@email.com',
    phone: '+254 777 678 901',
    idNumber: '55555555',
    property: 'Sunset Apartments',
    propertyId: '1',
    landlordId: '1',
    unit: '2B',
    rent: 40000,
    status: 'Active',
    moveIn: '2023-05-20',
    moveOut: null,
    leaseEnd: '2025-05-19',
    emergencyContact: 'Anne Taylor',
    emergencyPhone: '+254 777 777 777',
  },
  {
    id: '8',
    name: 'Maria Garcia',
    email: 'maria.g@email.com',
    phone: '+254 788 890 123',
    idNumber: '66666666',
    property: 'Garden Estate',
    propertyId: '4',
    landlordId: '4',
    unit: '3H',
    rent: 36000,
    status: 'Active',
    moveIn: '2023-08-01',
    moveOut: null,
    leaseEnd: '2025-07-31',
    emergencyContact: 'Carlos Garcia',
    emergencyPhone: '+254 788 888 888',
  },
]

export const mockLandlords = [
  {
    id: '1',
    name: 'James K. Johnson',
    email: 'james.johnson@email.com',
    phone: '+254 700 111 222',
    idNumber: 'LD001',
    properties: ['1'],
    totalUnits: 8,
    totalTenants: 8,
    status: 'Active',
    bankAccount: 'Kenya Commercial Bank',
    accountNumber: '1234567890',
    taxId: 'P051234567A',
  },
  {
    id: '2',
    name: 'Sarah M. Williams',
    email: 'sarah.williams@email.com',
    phone: '+254 700 333 444',
    idNumber: 'LD002',
    properties: ['2'],
    totalUnits: 12,
    totalTenants: 8,
    status: 'Active',
    bankAccount: 'Equity Bank',
    accountNumber: '0987654321',
    taxId: 'P051234568A',
  },
  {
    id: '3',
    name: 'Robert J. Brown',
    email: 'robert.brown@email.com',
    phone: '+254 700 555 666',
    idNumber: 'LD003',
    properties: ['3'],
    totalUnits: 6,
    totalTenants: 3,
    status: 'Active',
    bankAccount: 'NCBA Bank',
    accountNumber: '5555555555',
    taxId: 'P051234569A',
  },
  {
    id: '4',
    name: 'Patricia L. Davis',
    email: 'patricia.davis@email.com',
    phone: '+254 700 777 888',
    idNumber: 'LD004',
    properties: ['4'],
    totalUnits: 10,
    totalTenants: 9,
    status: 'Active',
    bankAccount: 'Standard Chartered Bank',
    accountNumber: '6666666666',
    taxId: 'P051234570A',
  },
]

export const mockAdmins = [
  {
    id: '1',
    name: 'Alice Johnson',
    email: 'alice.admin@propmanage.com',
    phone: '+254 700 999 000',
    role: 'Super Admin',
    department: 'Administration',
    status: 'Active',
    permissions: ['all'],
  },
  {
    id: '2',
    name: 'Bob Smith',
    email: 'bob.admin@propmanage.com',
    phone: '+254 700 888 111',
    role: 'Property Manager',
    department: 'Properties',
    status: 'Active',
    permissions: ['properties', 'tenants', 'leases', 'maintenance'],
  },
  {
    id: '3',
    name: 'Carol White',
    email: 'carol.admin@propmanage.com',
    phone: '+254 700 777 222',
    role: 'Finance Manager',
    department: 'Finance',
    status: 'Active',
    permissions: ['payments', 'financial-reports', 'invoices'],
  },
]

export const mockVendorUsers = [
  {
    id: '1',
    vendorId: '1',
    name: 'Quick Repairs Ltd',
    email: 'info@quickrepairs.com',
    phone: '+254 722 100 200',
    role: 'Vendor Admin',
    status: 'Active',
  },
  {
    id: '2',
    vendorId: '2',
    name: 'Professional Cleaners',
    email: 'clean@profclean.com',
    phone: '+254 722 300 400',
    role: 'Vendor Admin',
    status: 'Active',
  },
  {
    id: '3',
    vendorId: '3',
    name: 'Premier Security Services',
    email: 'security@premier.com',
    phone: '+254 722 500 600',
    role: 'Vendor Admin',
    status: 'Active',
  },
  {
    id: '4',
    vendorId: '4',
    name: 'Landscape Designs',
    email: 'landscape@designs.com',
    phone: '+254 722 700 800',
    role: 'Vendor Admin',
    status: 'Active',
  },
  {
    id: '5',
    vendorId: '5',
    name: 'Fix-It Fast Services',
    email: 'contact@fixitfast.com',
    phone: '+254 722 900 100',
    role: 'Vendor Admin',
    status: 'Active',
  },
]

export const mockVendors = [
  {
    id: '1',
    name: 'Quick Repairs Ltd',
    email: 'info@quickrepairs.com',
    phone: '+254 722 100 200',
    category: 'Maintenance',
    specialization: 'Plumbing, Electrical, General Repairs',
    status: 'Active',
    rating: 4.8,
    serviceArea: 'Downtown, Uptown',
  },
  {
    id: '2',
    name: 'Professional Cleaners',
    email: 'clean@profclean.com',
    phone: '+254 722 300 400',
    category: 'Cleaning',
    specialization: 'Apartment Cleaning, Carpet Cleaning',
    status: 'Active',
    rating: 4.6,
    serviceArea: 'All Areas',
  },
  {
    id: '3',
    name: 'Premier Security Services',
    email: 'security@premier.com',
    phone: '+254 722 500 600',
    category: 'Security',
    specialization: 'CCTV, Guards, Patrols',
    status: 'Active',
    rating: 4.9,
    serviceArea: 'Downtown, Midtown, Riverside',
  },
  {
    id: '4',
    name: 'Landscape Designs',
    email: 'landscape@designs.com',
    phone: '+254 722 700 800',
    category: 'Landscaping',
    specialization: 'Garden Design, Maintenance',
    status: 'Active',
    rating: 4.7,
    serviceArea: 'Uptown, Riverside',
  },
]

export const mockBuyers = [
  {
    id: '1',
    name: 'Investment Group Kenya',
    email: 'invest@igkenya.com',
    phone: '+254 700 200 300',
    type: 'Corporate Buyer',
    interestedProperties: ['2', '4'],
    budget: 50000000,
    status: 'Active',
    contactPerson: 'Mr. Kipchoge',
  },
  {
    id: '2',
    name: 'John Kariuki',
    email: 'john.kariuki@email.com',
    phone: '+254 700 400 500',
    type: 'Individual',
    interestedProperties: ['1'],
    budget: 8000000,
    status: 'Active',
    contactPerson: 'John Kariuki',
  },
  {
    id: '3',
    name: 'Real Estate Development Co',
    email: 'dev@redco.com',
    phone: '+254 700 600 700',
    type: 'Corporate Buyer',
    interestedProperties: ['3'],
    budget: 15000000,
    status: 'Active',
    contactPerson: 'Ms. Njeri',
  },
]

export const mockPayments = [
  // November 2024 Rent Payments
  {
    id: 'P001',
    leaseId: '1',
    tenantId: '1',
    tenantName: 'John Smith',
    propertyId: '1',
    propertyName: 'Sunset Apartments',
    landlordId: '1',
    landlordName: 'Robert Johnson',
    unit: '5A',
    amount: 40000,
    type: 'RENT',
    status: 'COMPLETED',
    method: 'M-Pesa',
    reference: 'RKJ8H9L2M4',
    dueDate: '2024-11-01',
    paidDate: '2024-11-01T08:15:00',
    month: 'November 2024',
    createdAt: '2024-10-25T10:00:00',
  },
  {
    id: 'P002',
    leaseId: '2',
    tenantId: '2',
    tenantName: 'Sarah Johnson',
    propertyId: '2',
    propertyName: 'Vista Plaza',
    landlordId: '2',
    landlordName: 'Sarah Davis',
    unit: '3B',
    amount: 40000,
    type: 'RENT',
    status: 'COMPLETED',
    method: 'Bank Transfer',
    reference: 'BT20241105001',
    dueDate: '2024-11-05',
    paidDate: '2024-11-05T14:30:00',
    month: 'November 2024',
    createdAt: '2024-10-28T10:00:00',
  },
  {
    id: 'P003',
    leaseId: '3',
    tenantId: '3',
    tenantName: 'Michael Chen',
    propertyId: '3',
    propertyName: 'Highland House',
    landlordId: '3',
    landlordName: 'Michael Brown',
    unit: '2C',
    amount: 30000,
    type: 'RENT',
    status: 'OVERDUE',
    method: null,
    reference: null,
    dueDate: '2024-11-01',
    paidDate: null,
    month: 'November 2024',
    createdAt: '2024-10-25T10:00:00',
  },
  {
    id: 'P004',
    leaseId: '4',
    tenantId: '4',
    tenantName: 'Emma Wilson',
    propertyId: '1',
    propertyName: 'Sunset Apartments',
    landlordId: '1',
    landlordName: 'Robert Johnson',
    unit: '8D',
    amount: 40000,
    type: 'RENT',
    status: 'COMPLETED',
    method: 'M-Pesa',
    reference: 'RLM3N5P7Q9',
    dueDate: '2024-11-01',
    paidDate: '2024-11-02T09:45:00',
    month: 'November 2024',
    createdAt: '2024-10-25T10:00:00',
  },
  {
    id: 'P005',
    leaseId: '5',
    tenantId: '5',
    tenantName: 'David Martinez',
    propertyId: '4',
    propertyName: 'Garden Estate',
    landlordId: '4',
    landlordName: 'Emily Taylor',
    unit: '6F',
    amount: 36000,
    type: 'RENT',
    status: 'COMPLETED',
    method: 'Cash',
    reference: 'CASH20241110',
    dueDate: '2024-11-10',
    paidDate: '2024-11-10T11:00:00',
    month: 'November 2024',
    createdAt: '2024-11-03T10:00:00',
  },
  {
    id: 'P006',
    leaseId: '6',
    tenantId: '6',
    tenantName: 'Lisa Anderson',
    propertyId: '2',
    propertyName: 'Vista Plaza',
    landlordId: '2',
    landlordName: 'Sarah Davis',
    unit: '7E',
    amount: 40000,
    type: 'RENT',
    status: 'PENDING',
    method: null,
    reference: null,
    dueDate: '2024-11-15',
    paidDate: null,
    month: 'November 2024',
    createdAt: '2024-11-08T10:00:00',
  },
  // October 2024 Rent Payments
  {
    id: 'P007',
    leaseId: '1',
    tenantId: '1',
    tenantName: 'John Smith',
    propertyId: '1',
    propertyName: 'Sunset Apartments',
    landlordId: '1',
    landlordName: 'Robert Johnson',
    unit: '5A',
    amount: 40000,
    type: 'RENT',
    status: 'COMPLETED',
    method: 'M-Pesa',
    reference: 'RKJ1A2B3C4',
    dueDate: '2024-10-01',
    paidDate: '2024-10-01T07:30:00',
    month: 'October 2024',
    createdAt: '2024-09-25T10:00:00',
  },
  {
    id: 'P008',
    leaseId: '2',
    tenantId: '2',
    tenantName: 'Sarah Johnson',
    propertyId: '2',
    propertyName: 'Vista Plaza',
    landlordId: '2',
    landlordName: 'Sarah Davis',
    unit: '3B',
    amount: 40000,
    type: 'RENT',
    status: 'COMPLETED',
    method: 'Bank Transfer',
    reference: 'BT20241005002',
    dueDate: '2024-10-05',
    paidDate: '2024-10-05T13:15:00',
    month: 'October 2024',
    createdAt: '2024-09-28T10:00:00',
  },
  {
    id: 'P009',
    leaseId: '3',
    tenantId: '3',
    tenantName: 'Michael Chen',
    propertyId: '3',
    propertyName: 'Highland House',
    landlordId: '3',
    landlordName: 'Michael Brown',
    unit: '2C',
    amount: 30000,
    type: 'RENT',
    status: 'COMPLETED',
    method: 'M-Pesa',
    reference: 'RMC4D5E6F7',
    dueDate: '2024-10-01',
    paidDate: '2024-10-03T10:20:00',
    month: 'October 2024',
    createdAt: '2024-09-25T10:00:00',
  },
  {
    id: 'P010',
    leaseId: '4',
    tenantId: '4',
    tenantName: 'Emma Wilson',
    propertyId: '1',
    propertyName: 'Sunset Apartments',
    landlordId: '1',
    landlordName: 'Robert Johnson',
    unit: '8D',
    amount: 40000,
    type: 'RENT',
    status: 'COMPLETED',
    method: 'M-Pesa',
    reference: 'REW7G8H9I0',
    dueDate: '2024-10-01',
    paidDate: '2024-10-01T08:00:00',
    month: 'October 2024',
    createdAt: '2024-09-25T10:00:00',
  },
  // Deposit Payments
  {
    id: 'P011',
    leaseId: '1',
    tenantId: '1',
    tenantName: 'John Smith',
    propertyId: '1',
    propertyName: 'Sunset Apartments',
    landlordId: '1',
    landlordName: 'Robert Johnson',
    unit: '5A',
    amount: 80000,
    type: 'DEPOSIT',
    status: 'COMPLETED',
    method: 'Bank Transfer',
    reference: 'BT20230615DEP',
    dueDate: '2023-06-15',
    paidDate: '2023-06-14T15:00:00',
    month: 'June 2023',
    createdAt: '2023-06-01T10:00:00',
  },
  {
    id: 'P012',
    leaseId: '2',
    tenantId: '2',
    tenantName: 'Sarah Johnson',
    propertyId: '2',
    propertyName: 'Vista Plaza',
    landlordId: '2',
    landlordName: 'Sarah Davis',
    unit: '3B',
    amount: 80000,
    type: 'DEPOSIT',
    status: 'COMPLETED',
    method: 'M-Pesa',
    reference: 'RSJ1J2K3L4',
    dueDate: '2023-08-22',
    paidDate: '2023-08-21T12:30:00',
    month: 'August 2023',
    createdAt: '2023-08-10T14:30:00',
  },
  // Utility Payments
  {
    id: 'P013',
    leaseId: '1',
    tenantId: '1',
    tenantName: 'John Smith',
    propertyId: '1',
    propertyName: 'Sunset Apartments',
    landlordId: '1',
    landlordName: 'Robert Johnson',
    unit: '5A',
    amount: 3500,
    type: 'UTILITIES',
    status: 'COMPLETED',
    method: 'M-Pesa',
    reference: 'RKJ5M6N7O8',
    dueDate: '2024-11-05',
    paidDate: '2024-11-05T10:15:00',
    month: 'November 2024',
    createdAt: '2024-11-01T10:00:00',
  },
  {
    id: 'P014',
    leaseId: '2',
    tenantId: '2',
    tenantName: 'Sarah Johnson',
    propertyId: '2',
    propertyName: 'Vista Plaza',
    landlordId: '2',
    landlordName: 'Sarah Davis',
    unit: '3B',
    amount: 4200,
    type: 'UTILITIES',
    status: 'PENDING',
    method: null,
    reference: null,
    dueDate: '2024-11-10',
    paidDate: null,
    month: 'November 2024',
    createdAt: '2024-11-05T10:00:00',
  },
]

export const mockMaintenanceRequests = [
  {
    id: '1',
    tenantName: 'John Smith',
    tenantId: '1',
    landlordId: '1',
    property: 'Sunset Apartments',
    propertyId: '1',
    unit: '5A',
    issue: 'Leaky kitchen faucet',
    priority: 'Medium',
    status: 'In Progress',
    dateSubmitted: '2024-11-10',
    vendorId: '1',
    vendorName: 'Quick Repairs Ltd',
    estimatedCost: 2500,
  },
  {
    id: '2',
    tenantName: 'Sarah Johnson',
    tenantId: '2',
    landlordId: '2',
    property: 'Vista Plaza',
    propertyId: '2',
    unit: '3B',
    issue: 'AC not cooling',
    priority: 'High',
    status: 'Scheduled',
    dateSubmitted: '2024-11-11',
    vendorId: '1',
    vendorName: 'Quick Repairs Ltd',
    estimatedCost: 5000,
  },
  {
    id: '3',
    tenantName: 'Michael Chen',
    tenantId: '3',
    landlordId: '3',
    property: 'Highland House',
    propertyId: '3',
    unit: '2C',
    issue: 'Broken door lock',
    priority: 'High',
    status: 'Completed',
    dateSubmitted: '2024-11-08',
    vendorId: '1',
    vendorName: 'Quick Repairs Ltd',
    estimatedCost: 1500,
  },
]

export const mockLeases = [
  {
    id: '1',
    tenantId: '1',
    tenantName: 'John Smith',
    propertyId: '1',
    propertyName: 'Sunset Apartments',
    landlordId: '1',
    landlordName: 'Robert Johnson',
    unit: '5A',
    startDate: '2023-06-15',
    endDate: '2025-06-14',
    monthlyRent: 40000,
    deposit: 80000,
    status: 'Active',
    type: 'Fixed-Term',
    autoRenew: false,
    paymentDay: 1,
    termsFile: '/leases/lease-001.pdf',
    createdAt: '2023-06-01T10:00:00',
  },
  {
    id: '2',
    tenantId: '2',
    tenantName: 'Sarah Johnson',
    propertyId: '2',
    propertyName: 'Vista Plaza',
    landlordId: '2',
    landlordName: 'Sarah Davis',
    unit: '3B',
    startDate: '2023-08-22',
    endDate: '2025-08-21',
    monthlyRent: 40000,
    deposit: 80000,
    status: 'Active',
    type: 'Fixed-Term',
    autoRenew: true,
    paymentDay: 5,
    termsFile: '/leases/lease-002.pdf',
    createdAt: '2023-08-10T14:30:00',
  },
  {
    id: '3',
    tenantId: '3',
    tenantName: 'Michael Chen',
    propertyId: '3',
    propertyName: 'Highland House',
    landlordId: '3',
    landlordName: 'Michael Brown',
    unit: '2C',
    startDate: '2023-11-01',
    endDate: '2025-10-31',
    monthlyRent: 30000,
    deposit: 60000,
    status: 'Active',
    type: 'Fixed-Term',
    autoRenew: false,
    paymentDay: 1,
    termsFile: '/leases/lease-003.pdf',
    createdAt: '2023-10-20T09:15:00',
  },
  {
    id: '4',
    tenantId: '4',
    tenantName: 'Emma Wilson',
    propertyId: '1',
    propertyName: 'Sunset Apartments',
    landlordId: '1',
    landlordName: 'Robert Johnson',
    unit: '8D',
    startDate: '2023-09-15',
    endDate: '2025-09-14',
    monthlyRent: 40000,
    deposit: 80000,
    status: 'Active',
    type: 'Fixed-Term',
    autoRenew: true,
    paymentDay: 1,
    termsFile: '/leases/lease-004.pdf',
    createdAt: '2023-09-01T11:20:00',
  },
  {
    id: '5',
    tenantId: '5',
    tenantName: 'David Martinez',
    propertyId: '4',
    propertyName: 'Garden Estate',
    landlordId: '4',
    landlordName: 'Emily Taylor',
    unit: '6F',
    startDate: '2023-07-10',
    endDate: '2025-07-09',
    monthlyRent: 36000,
    deposit: 72000,
    status: 'Active',
    type: 'Fixed-Term',
    autoRenew: false,
    paymentDay: 10,
    termsFile: '/leases/lease-005.pdf',
    createdAt: '2023-06-25T16:45:00',
  },
  {
    id: '6',
    tenantId: '6',
    tenantName: 'Lisa Anderson',
    propertyId: '2',
    propertyName: 'Vista Plaza',
    landlordId: '2',
    landlordName: 'Sarah Davis',
    unit: '7E',
    startDate: '2024-01-15',
    endDate: '2026-01-14',
    monthlyRent: 40000,
    deposit: 80000,
    status: 'Active',
    type: 'Fixed-Term',
    autoRenew: true,
    paymentDay: 15,
    termsFile: '/leases/lease-006.pdf',
    createdAt: '2024-01-05T13:00:00',
  },
]

export const mockNotifications = [
  {
    id: '1',
    type: 'payment',
    title: 'Payment Due',
    message: 'Your rent for November is due on November 1st',
    date: '2024-10-25',
    read: false,
    userId: '1',
  },
  {
    id: '2',
    type: 'maintenance',
    title: 'Maintenance Completed',
    message: 'Your maintenance request has been completed',
    date: '2024-11-09',
    read: true,
    userId: '1',
  },
  {
    id: '3',
    type: 'lease',
    title: 'Lease Renewal',
    message: 'Your lease will expire in 6 months. Renewal terms available.',
    date: '2024-11-01',
    read: true,
    userId: '3',
  },
  {
    id: '4',
    type: 'payment',
    title: 'Payment Received',
    message: 'Payment of KSh 40,000 received from John Smith',
    date: '2024-11-05',
    read: false,
    userId: 'LD001',
  },
  {
    id: '5',
    type: 'vendor',
    title: 'Service Request',
    message: 'New maintenance request assigned to your company',
    date: '2024-11-11',
    read: true,
    userId: 'V1',
  },
]

export const mockInvoices = [
  {
    id: 'INV001',
    landlordId: '1',
    landlordName: 'James K. Johnson',
    amount: 80000,
    period: 'November 2024',
    dueDate: '2024-11-30',
    status: 'Paid',
    items: [
      { description: 'Unit 5A - John Smith', amount: 40000 },
      { description: 'Unit 8D - Emma Wilson', amount: 40000 },
    ],
  },
  {
    id: 'INV002',
    landlordId: '2',
    landlordName: 'Sarah M. Williams',
    amount: 80000,
    period: 'November 2024',
    dueDate: '2024-11-30',
    status: 'Pending',
    items: [
      { description: 'Unit 3B - Sarah Johnson', amount: 40000 },
      { description: 'Unit 9G - Lisa Anderson', amount: 40000 },
    ],
  },
]

// ============================================================================
// HELPER FUNCTIONS - Query relationships between entities
// ============================================================================

// Get entity by ID
export const getLandlordById = (id: string) => mockLandlords.find(l => l.id === id)
export const getPropertyById = (id: string) => mockProperties.find(p => p.id === id)
export const getTenantById = (id: string) => mockTenants.find(t => t.id === id)
export const getVendorById = (id: string) => mockVendors.find(v => v.id === id)

// Get related entities
export const getPropertiesByLandlordId = (landlordId: string) => 
  mockProperties.filter(p => p.landlordId === landlordId)

export const getTenantsByLandlordId = (landlordId: string) =>
  mockTenants.filter(t => t.landlordId === landlordId)

export const getTenantsByPropertyId = (propertyId: string) =>
  mockTenants.filter(t => t.propertyId === propertyId)

export const getPaymentsByTenantId = (tenantId: string) =>
  mockPayments.filter(p => p.tenantId === tenantId)

export const getPaymentsByLandlordId = (landlordId: string) =>
  mockPayments.filter(p => p.landlordId === landlordId)

export const getPaymentsByPropertyId = (propertyId: string) =>
  mockPayments.filter(p => p.propertyId === propertyId)

export const getMaintenanceByTenantId = (tenantId: string) =>
  mockMaintenanceRequests.filter(m => m.tenantId === tenantId)

export const getMaintenanceByLandlordId = (landlordId: string) =>
  mockMaintenanceRequests.filter(m => m.landlordId === landlordId)

export const getMaintenanceByPropertyId = (propertyId: string) =>
  mockMaintenanceRequests.filter(m => m.propertyId === propertyId)

export const getLeaseByTenantId = (tenantId: string) =>
  mockLeases.find(l => l.tenantId === tenantId)

export const getLeasesByLandlordId = (landlordId: string) =>
  mockLeases.filter(l => l.landlordId === landlordId)

export const getLeasesByPropertyId = (propertyId: string) =>
  mockLeases.filter(l => l.propertyId === propertyId)

// Calculate statistics
export const getPropertyStats = (propertyId: string) => {
  const property = getPropertyById(propertyId)
  const tenants = getTenantsByPropertyId(propertyId)
  const payments = getPaymentsByPropertyId(propertyId)
  
  if (!property) return null
  
  const currentMonthPayments = payments.filter(p => p.month === 'November 2024' && p.status === 'Paid')
  const totalCollected = currentMonthPayments.reduce((sum, p) => sum + p.amount, 0)
  
  return {
    totalUnits: property.units,
    occupiedUnits: property.occupied,
    vacantUnits: property.units - property.occupied,
    occupancyRate: (property.occupied / property.units) * 100,
    totalRent: property.totalRent,
    collectedThisMonth: totalCollected,
    tenantCount: tenants.length,
  }
}

export const getLandlordStats = (landlordId: string) => {
  const properties = getPropertiesByLandlordId(landlordId)
  const tenants = getTenantsByLandlordId(landlordId)
  const payments = getPaymentsByLandlordId(landlordId)
  
  const totalUnits = properties.reduce((sum, p) => sum + p.units, 0)
  const occupiedUnits = properties.reduce((sum, p) => sum + p.occupied, 0)
  const totalRent = properties.reduce((sum, p) => sum + p.totalRent, 0)
  
  const paidPayments = payments.filter(p => 
    p.status === 'Paid' && p.month === 'November 2024'
  )
  const pendingPayments = payments.filter(p => 
    p.status === 'Pending' && p.month === 'November 2024'
  )
  
  return {
    totalProperties: properties.length,
    totalUnits,
    occupiedUnits,
    vacantUnits: totalUnits - occupiedUnits,
    occupancyRate: (occupiedUnits / totalUnits) * 100,
    totalTenants: tenants.length,
    monthlyRevenue: totalRent,
    collectedThisMonth: paidPayments.reduce((sum, p) => sum + p.amount, 0),
    pendingThisMonth: pendingPayments.reduce((sum, p) => sum + p.amount, 0),
  }
}

export const getTenantStats = (tenantId: string) => {
  const tenant = getTenantById(tenantId)
  const payments = getPaymentsByTenantId(tenantId)
  const maintenance = getMaintenanceByTenantId(tenantId)
  const lease = getLeaseByTenantId(tenantId)
  
  if (!tenant) return null
  
  const paidPayments = payments.filter(p => p.status === 'Paid')
  const pendingPayments = payments.filter(p => p.status === 'Pending' || p.status === 'Overdue')
  
  return {
    monthlyRent: tenant.rent,
    totalPaid: paidPayments.reduce((sum, p) => sum + p.amount, 0),
    totalPending: pendingPayments.reduce((sum, p) => sum + p.amount, 0),
    maintenanceRequests: maintenance.length,
    openMaintenanceRequests: maintenance.filter(m => m.status !== 'Completed').length,
    leaseEndDate: tenant.leaseEnd,
    daysUntilLeaseEnd: Math.ceil((new Date(tenant.leaseEnd).getTime() - new Date().getTime()) / (1000 * 60 * 60 * 24)),
  }
}

// Mock Rent Transactions
export const mockRentTransactions = [
  {
    id: '1',
    paymentId: '1',
    leaseId: '1',
    landlordId: '1',
    propertyId: '1',
    tenantId: '1',
    grossRent: 40000,
    serviceCharge: 4000,
    managementFee: 3200,
    maintenanceFees: 2000,
    otherDeductions: 0,
    totalDeductions: 9200,
    netAmount: 30800,
    lateFees: 0,
    rentPeriod: 'November 2025',
    paidDate: '2025-11-05T10:00:00Z',
    payoutStatus: 'PAID',
    payoutId: '1',
    payoutDate: '2025-11-15T14:00:00Z',
    payoutReference: 'PAY-2025-11-001',
    paymentMethod: 'BANK_TRANSFER',
    propertyName: 'Sunset Apartments',
    unitId: '5A',
    tenantName: 'John Smith',
    createdAt: '2025-11-05T10:00:00Z',
    updatedAt: '2025-11-15T14:00:00Z',
  },
  {
    id: '2',
    paymentId: '2',
    leaseId: '2',
    landlordId: '1',
    propertyId: '1',
    tenantId: '2',
    grossRent: 40000,
    serviceCharge: 4000,
    managementFee: 3200,
    maintenanceFees: 0,
    otherDeductions: 0,
    totalDeductions: 7200,
    netAmount: 32800,
    lateFees: 0,
    rentPeriod: 'November 2025',
    paidDate: '2025-11-03T09:30:00Z',
    payoutStatus: 'PAID',
    payoutId: '1',
    payoutDate: '2025-11-15T14:00:00Z',
    payoutReference: 'PAY-2025-11-001',
    paymentMethod: 'BANK_TRANSFER',
    propertyName: 'Sunset Apartments',
    unitId: '3B',
    tenantName: 'Sarah Johnson',
    createdAt: '2025-11-03T09:30:00Z',
    updatedAt: '2025-11-15T14:00:00Z',
  },
  {
    id: '3',
    paymentId: '3',
    leaseId: '3',
    landlordId: '1',
    propertyId: '1',
    tenantId: '3',
    grossRent: 40000,
    serviceCharge: 4000,
    managementFee: 3200,
    maintenanceFees: 1500,
    otherDeductions: 0,
    totalDeductions: 8700,
    netAmount: 31300,
    lateFees: 2000,
    rentPeriod: 'October 2025',
    paidDate: '2025-10-08T11:00:00Z',
    payoutStatus: 'PAID',
    payoutId: '2',
    payoutDate: '2025-10-20T14:00:00Z',
    payoutReference: 'PAY-2025-10-001',
    paymentMethod: 'BANK_TRANSFER',
    propertyName: 'Sunset Apartments',
    unitId: '7C',
    tenantName: 'Michael Chen',
    createdAt: '2025-10-08T11:00:00Z',
    updatedAt: '2025-10-20T14:00:00Z',
  },
  {
    id: '4',
    paymentId: '4',
    leaseId: '4',
    landlordId: '2',
    propertyId: '2',
    tenantId: '4',
    grossRent: 40000,
    serviceCharge: 4000,
    managementFee: 3200,
    maintenanceFees: 0,
    otherDeductions: 0,
    totalDeductions: 7200,
    netAmount: 32800,
    lateFees: 0,
    rentPeriod: 'November 2025',
    paidDate: '2025-11-02T08:45:00Z',
    payoutStatus: 'PROCESSING',
    payoutId: '3',
    payoutDate: null,
    payoutReference: null,
    paymentMethod: 'BANK_TRANSFER',
    propertyName: 'Vista Plaza',
    unitId: '2A',
    tenantName: 'Emily Wilson',
    createdAt: '2025-11-02T08:45:00Z',
    updatedAt: '2025-11-10T10:00:00Z',
  },
  {
    id: '5',
    paymentId: '5',
    leaseId: '5',
    landlordId: '2',
    propertyId: '2',
    tenantId: '5',
    grossRent: 40000,
    serviceCharge: 4000,
    managementFee: 3200,
    maintenanceFees: 3000,
    otherDeductions: 500,
    totalDeductions: 10700,
    netAmount: 29300,
    lateFees: 0,
    rentPeriod: 'November 2025',
    paidDate: '2025-11-01T07:30:00Z',
    payoutStatus: 'PROCESSING',
    payoutId: '3',
    payoutDate: null,
    payoutReference: null,
    paymentMethod: 'BANK_TRANSFER',
    propertyName: 'Vista Plaza',
    unitId: '4B',
    tenantName: 'David Martinez',
    createdAt: '2025-11-01T07:30:00Z',
    updatedAt: '2025-11-10T10:00:00Z',
  },
]

// Mock Landlord Statements
export const mockLandlordStatements = [
  {
    id: '1',
    landlordId: '1',
    propertyId: null, // All properties
    period: 'November 2025',
    startDate: '2025-11-01T00:00:00Z',
    endDate: '2025-11-30T23:59:59Z',
    totalGrossRent: 120000,
    totalServiceCharges: 12000,
    totalManagementFees: 9600,
    totalMaintenanceFees: 2000,
    totalOtherDeductions: 0,
    totalDeductions: 23600,
    totalNetAmount: 96400,
    transactionCount: 3,
    propertyCount: 1,
    generatedAt: '2025-11-16T10:00:00Z',
    pdfUrl: null,
    sentAt: null,
    createdAt: '2025-11-16T10:00:00Z',
    updatedAt: '2025-11-16T10:00:00Z',
    transactions: [
      {
        id: '1',
        propertyName: 'Sunset Apartments',
        unitId: '5A',
        tenantName: 'John Smith',
        rentPeriod: 'November 2025',
        grossRent: 40000,
        deductions: {
          serviceCharge: 4000,
          managementFee: 3200,
          maintenance: 2000,
          other: 0,
          total: 9200,
        },
        netAmount: 30800,
        payoutStatus: 'PAID',
      },
      {
        id: '2',
        propertyName: 'Sunset Apartments',
        unitId: '3B',
        tenantName: 'Sarah Johnson',
        rentPeriod: 'November 2025',
        grossRent: 40000,
        deductions: {
          serviceCharge: 4000,
          managementFee: 3200,
          maintenance: 0,
          other: 0,
          total: 7200,
        },
        netAmount: 32800,
        payoutStatus: 'PAID',
      },
      {
        id: '3',
        propertyName: 'Sunset Apartments',
        unitId: '7C',
        tenantName: 'Michael Chen',
        rentPeriod: 'November 2025',
        grossRent: 40000,
        deductions: {
          serviceCharge: 4000,
          managementFee: 3200,
          maintenance: 0,
          other: 0,
          total: 7200,
        },
        netAmount: 32800,
        payoutStatus: 'PAID',
      },
    ],
    propertyBreakdown: [
      {
        propertyId: '1',
        propertyName: 'Sunset Apartments',
        unitCount: 3,
        grossRent: 120000,
        deductions: 23600,
        netAmount: 96400,
      },
    ],
  },
  {
    id: '2',
    landlordId: '1',
    propertyId: null,
    period: 'October 2025',
    startDate: '2025-10-01T00:00:00Z',
    endDate: '2025-10-31T23:59:59Z',
    totalGrossRent: 120000,
    totalServiceCharges: 12000,
    totalManagementFees: 9600,
    totalMaintenanceFees: 1500,
    totalOtherDeductions: 0,
    totalDeductions: 23100,
    totalNetAmount: 96900,
    transactionCount: 3,
    propertyCount: 1,
    generatedAt: '2025-11-01T10:00:00Z',
    pdfUrl: '/statements/landlord-1-october-2025.pdf',
    sentAt: '2025-11-01T11:00:00Z',
    createdAt: '2025-11-01T10:00:00Z',
    updatedAt: '2025-11-01T11:00:00Z',
    transactions: [],
    propertyBreakdown: [
      {
        propertyId: '1',
        propertyName: 'Sunset Apartments',
        unitCount: 3,
        grossRent: 120000,
        deductions: 23100,
        netAmount: 96900,
      },
    ],
  },
  {
    id: '3',
    landlordId: '1',
    propertyId: null,
    period: 'September 2025',
    startDate: '2025-09-01T00:00:00Z',
    endDate: '2025-09-30T23:59:59Z',
    totalGrossRent: 120000,
    totalServiceCharges: 12000,
    totalManagementFees: 9600,
    totalMaintenanceFees: 3500,
    totalOtherDeductions: 0,
    totalDeductions: 25100,
    totalNetAmount: 94900,
    transactionCount: 3,
    propertyCount: 1,
    generatedAt: '2025-10-01T10:00:00Z',
    pdfUrl: '/statements/landlord-1-september-2025.pdf',
    sentAt: '2025-10-01T11:00:00Z',
    createdAt: '2025-10-01T10:00:00Z',
    updatedAt: '2025-10-01T11:00:00Z',
    transactions: [],
    propertyBreakdown: [],
  },
  {
    id: '4',
    landlordId: '2',
    propertyId: null,
    period: 'November 2025',
    startDate: '2025-11-01T00:00:00Z',
    endDate: '2025-11-30T23:59:59Z',
    totalGrossRent: 80000,
    totalServiceCharges: 8000,
    totalManagementFees: 6400,
    totalMaintenanceFees: 3000,
    totalOtherDeductions: 500,
    totalDeductions: 17900,
    totalNetAmount: 62100,
    transactionCount: 2,
    propertyCount: 1,
    generatedAt: '2025-11-16T10:00:00Z',
    pdfUrl: null,
    sentAt: null,
    createdAt: '2025-11-16T10:00:00Z',
    updatedAt: '2025-11-16T10:00:00Z',
    transactions: [
      {
        id: '4',
        propertyName: 'Vista Plaza',
        unitId: '2A',
        tenantName: 'Emily Wilson',
        rentPeriod: 'November 2025',
        grossRent: 40000,
        deductions: {
          serviceCharge: 4000,
          managementFee: 3200,
          maintenance: 0,
          other: 0,
          total: 7200,
        },
        netAmount: 32800,
        payoutStatus: 'PROCESSING',
      },
      {
        id: '5',
        propertyName: 'Vista Plaza',
        unitId: '4B',
        tenantName: 'David Martinez',
        rentPeriod: 'November 2025',
        grossRent: 40000,
        deductions: {
          serviceCharge: 4000,
          managementFee: 3200,
          maintenance: 3000,
          other: 500,
          total: 10700,
        },
        netAmount: 29300,
        payoutStatus: 'PROCESSING',
      },
    ],
    propertyBreakdown: [
      {
        propertyId: '2',
        propertyName: 'Vista Plaza',
        unitCount: 2,
        grossRent: 80000,
        deductions: 17900,
        netAmount: 62100,
      },
    ],
  },
]
